#!/bin/bash
set -e

apt-get update
apt-get upgrade
apt-get install build-essential git cmake python3-pip curl \
	python3-dev sudo \
	firefox-esr terminator sudo thefuck \
	gnome-shell i3 feh \
	-y

# neovim build prereqs
# build neovim from scratch for newer features
apt-get install ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip

mkdir -p ~/src
pushd ~/src
#ignore clone fails if the repo is already there
git clone --single-branch --branch v0.3.4 https://github.com/neovim/neovim || true
pushd neovim
rm -rf build
make clean
make CMAKE_BUILD_TYPE=Release
make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=/opt/neovim"
make install

[[ $PATH != *"/opt/neovim/bin"* ]] && export PATH="/opt/neovim/bin:$PATH"
popd
popd
