#!/bin/bash
DEST=~/.config/scottrc
BASHRC_INSERT="source $DEST/scottrc"
BASHRC_LAST_LINE=$(grep "." ~/.bashrc | tail -1)
echo $BASHRC_LAST_LINE

if [[ "$BASHRC_LAST_LINE" == "$BASHRC_INSERT" ]]; then
	echo "Detected stale environment, updating."
else
	echo "Detected fresh install."
	echo "$BASHRC_INSERT" >> ~/.bashrc
fi

echo
echo "Copying fresh scottrc"
echo

mkdir -p $DEST
cp -r src/* $DEST/

echo
echo "Appending custom scottrc"
echo
###
# vim
###

which vim > /dev/null
VIM_INSTALLED=$?
which nvim > /dev/null
NVIM_INSTALLED=$?

if [[ $NVIM_INSTALLED = 0 ]]; then
	echo "source $DEST/nvimrc" >> $DEST/scottrc
elif [[ $VIM_INSTALLED = 0 ]]; then
	echo "source $DEST/vimrc" >> $DEST/scottrc
else 
	echo "source $DEST/virc" >> $DEST/scottrc
fi

ln $DEST/init.vim ~/.vimrc
ln $DEST/init.vim ~/.config/init.vim

###
# GIT
###
gitversionfull=($(git --version))
if [[ $? -eq 0 ]]; then
	echo "Found a valid git installation"

	gitversion=${gitversionfull[-1]}
	requiredver="2.16.0"
	echo "git version is $gitversion"
	if [ "$(printf '%s\n%s\n' "$gitversion" "$requiredver" | sort -V | head -n1)" = "$requiredver" ]; then 
		echo "Git version greater than $requiredver"
	else
		echo "Found git version less than $requiredver, wrapping status save with status push."
		echo "source $DEST/gitrc" >> $DEST/scottrc
	fi

else
	echo "Git not found, skipping git configuration"
fi
