#!/bin/bash
BASHRC_INSERT="source ~/.config/scottrc"
BASHRC_LAST_LINE=$(grep "." ~/.bashrc | tail -1)

clean() {
	rm -rf ~/.config/nvim/
	rm -rf ~/.config/i3/
	rm -f ~/.config/scottrc
	rm -f ~/.config/gitrc
	rm -f ~/.gitconfig
	rm -f ~/.vimrc
}

baseInstall() {
	if [[ "$BASHRC_LAST_LINE" == "$BASHRC_INSERT" ]]; then
		echo "Detected stale environment, updating."
	else
		echo "Detected fresh install."
		echo "$BASHRC_INSERT" >> ~/.bashrc
	fi

	echo
	echo "Copying fresh scottrc"
	echo

	shopt -s dotglob
	cp -r home/* ~/
	shopt -u dotglob
}

configureNeovim() {
	###
	# vim
	###

	mkdir -p ~/.config/nvim/plugged/youcompleteme
	curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim > /dev/null 2>&1
	pip3 install --upgrade neovim
	nvim +'PlugInstall --sync' +qa
	pushd ~/.config/nvim/plugged/youcompleteme
		python3 install.py --clang-completer
	popd
}

configureGit() {
	###
	# git
	###
	gitversionfull=($(git --version))
	if [[ $? -eq 0 ]]; then
		echo "Found a valid git installation"

		gitversion=${gitversionfull[-1]}
		requiredver="2.16.0"
		echo "git version is $gitversion"
		if [ "$(printf '%s\n%s\n' "$gitversion" "$requiredver" | sort -V | head -n1)" = "$requiredver" ]; then
			echo "Git version greater than $requiredver"
		else
			echo "Found git version less than $requiredver, wrapping status save with status push."
			echo "source ~/.config/gitrc" >> ~/.config/scottrc
		fi

	else
		echo "Git not found, skipping git configuration"
	fi
}


if [[ $1 == "quick" || $1 == "q" ]]; then
	baseInstall
else
	clean
	baseInstall
	configureNeovim
	configureGit
fi

