#!/bin/bash

alias la='ls -a'
alias ll='ls -l'
alias update='sudo apt-get update && sudo apt-get upgrade'

alias poweroff='systemctl poweroff'
alias shutdown='systemctl poweroff'
alias restart='systemctl restart'
alias sleep='systemctl suspend'

export EDITOR=nvim
export VISUAL=nvim
export GIT_EDITOR=nvim

command vim > /dev/null 2>&1
if [[ $? != 0 ]]; then
	alias vim='nvim'
fi
alias bleh='echo fuck fuck fuck'
eval $(thefuck --alias)
