#!/bin/bash

alias la='ls -a'
alias ll='ls -l'
alias update='sudo apt-get update && sudo apt-get upgrade'

alias poweroff='systemctl poweroff'
alias shutdown='systemctl poweroff'
alias restart='systemctl restart'
alias sleep='systemctl suspend'

EDITOR=nvim
