#!/bin/bash
echo "downloading song: '$(xsel -b)'"
youtube-dl -x --audio-format mp3 --prefer-ffmpeg -o "~/Music/%(title)s-%(artist)s.%(ext)s" --restrict-filename $(xsel -b) || notify-send "failed to download '$(xsel -b)'"
