#!/bin/bash
set -e

installBase() {
	apt update -y
	apt upgrade -y
	NEOVIM="" # dummy variable, neovim is built from source so this just helps indicate what packages it depends on, these are my script dependencies rather than hard neovim dependencies
	# packages on the same line are dependencies
	apt install \
		chkrootkit \
		clamav clamav-daemon \
		build-essential \
		git \
		cmake \
		curl \
		xsel \
		thefuck python3-dev python3-pip python3-setuptools python-setuptools \
		sudo \
		$(NEOVIM) exuberant-ctags silversearcher-ag \
		youtube-dl \
		-y
}

installGUI() {
	# install firefox if on ubuntu, but prefer esr on debian
	apt install firefox-esr || apt install firefox -y
	apt install rxvt-unicode-256color \
		fonts-hack-ttf youtube-dl \
		i3 --no-install-recommends i3status i3lock dmenu dunst xorg xinit feh \
		gnome-shell \
		-y
	pip3 install lz4 # allows parsing of mozilla's modified json format
}

installVmware() {
	apt install \
		open-vm-tools open-vm-tools-desktop \
		-y
}

installVirtualbox() {
	# assumes the virtualbox installation media is already inserted into the virtualmachine
	apt install \
		build-essential module-assistant \
		-y
	m-a prepare

	bash /media/cdrom/VBoxLinuxAdditions.run
}

buildNeovim() {
	# neovim build prereqs
	# build neovim from scratch for newer features
	apt install ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip -y

	mkdir -p ~/src
	pushd ~/src
		rm -r neovim
		git clone --single-branch --branch v0.4.3 https://github.com/neovim/neovim
		pushd neovim
			rm -rf build
			make clean
			make CMAKE_BUILD_TYPE=Release
			make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=/opt/neovim"
			make install

			[[ $PATH != *"/opt/neovim/bin"* ]] && export PATH="/opt/neovim/bin:$PATH"
		popd
	popd
}

for ARG in "$@"
do
	if [[ $ARG == "base" ]]; then
		installBase
	elif [[ $ARG == "full" ]]; then
		installBase
		installGUI
		buildNeovim
	elif [[ $ARG == "vmw" ]] || [[ $ARG == "vmware" ]]; then
		installVmware
	elif [[ $ARG == "neovim" ]]; then
		buildNeovim
	elif [[ $ARG == "vb" ]] || [[ $ARG == "virtualbox" ]]; then
		installVirtualbox
	fi
done
